### ISSUE TITLE
CreateBurnCardViaCLI should describe where a aml_sdc_burn.ini can be got

### ISSUE THREAD

**Issue by kostousov-ds** [khadas/khadas_docs#114]
The page vim1/CreateBurnCardViaCLI should fully describe where one can get `aml_sdc_burn.ini` for upgrade to some linux image.
For example: I download a ubuntu-server image from https://docs.khadas.com/vim1/FirmwareUbuntu.html but I can't find info about `aml_sdc_burn.ini`.

**Comment by numbqq** [comment]
Hello @kostousov-ds 

You are right, we will update the docs.

You can find the file here: https://github.com/khadas/images_upgrade/blob/master/Amlogic/aml_sdc_burn.ini

**Note: This doc is only for Android.**

**Comment by kostousov-ds** [comment]
Only android? The page have no any words about android :-/
How to create a burn card with Ubuntu?

**Comment by numbqq** [comment]
Hello @kostousov-ds

For ubuntu, we don't use SD card to upgrade, so we haven't tested it...but you  can try
