### ISSUE TITLE
vim 3 NPU support for deep learning

### ISSUE THREAD

**Issue by Lebron8997** [khadas/khadas_docs#174]
I found tensorflow on page "https://docs.khadas.com/zh-cn/vim3/InstallTensorFlow.html",but only cpu supported. How to use npu for deep learning with npu on VIM 3 (5.0 TOPS?)
Thanks!

**Comment by nwuYS** [comment]
I was also interseted in this issue.

**Comment by nwuYS** [comment]
There are no office drivers.
