### ISSUE TITLE
No  u-boot.bin.sd.bin in firmware folder 

### ISSUE THREAD

**Issue by smartnode** [khadas/khadas_docs#185]
I need to burn Ubuntu on eMMC. However, I cannot find u-boot.bin.sd.bin as described in guide document in https://docs.khadas.com/vim3/CreateBurnCardViaCLI.html
https://dl.khadas.com/Firmware/VIM3/U-boot/ is empty.

**Comment by smartnode** [comment]
Also, can you please link boot.img, where it can be downloaded in https://docs.khadas.com/vim3/UBootUsage.html document.

**Comment by numbqq** [comment]
> I need to burn Ubuntu on eMMC. However, I cannot find u-boot.bin.sd.bin as described in guide document in

Please check here: https://docs.khadas.com/vim3/UpgradeViaUSBCable.html

**Comment by smartnode** [comment]
Thank you. This helped.

**Comment by Resun1971** [comment]
Hi! I've tried to use instruction above, but looks like the page is deleted, where I can find it now?
